config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :create]
  resources :weapons, only: [:index, :create, :destroy, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: [:knight, :wizard]

  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  def title
    "#{self.kind} #{self.nickname} ##{self.level}"
  end
end

app/models/weapon.rb
class Weapon < ApplicationRecord

  after_initialize :init
  validates_presence_of :name, :description

  def current_power
    power_base + ((level - 1) * power_step)
  end

  def title
    "#{name} ##{level}"
  end

  private

  def init
    self.level ||= 1
    self.power_base ||= 1000
    self.power_step ||= 100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def create
    @weapon = Weapon.create(weapons_params)
    redirect_to weapons_path
  end

  def destroy
    @weapon = Weapon.find(params[:id])
    if @weapon.destroy
      redirect_to weapons_path
    end
  end

  def show
    @weapon = Weapon.find(params[:id])
  end

  private

  def weapons_params
    params.require(:weapon).permit(:name, :description, :power_base, :power_step, :level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.title %></p>
<% end %>

app/views/weapons/index.html.erb
<% @weapons.each do |weapon| %>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Current Power</th>
      <th>Title</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= weapon.name %></td>
      <td><%= weapon.current_power %></td>
      <td><%= weapon.title %></td>
      <td>
        <%= link_to weapon_path(weapon) do %>
          <span>Show</span>
        <% end %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>

app/views/weapons/show.html.erb
<h1><%= @weapon.name %></h1>
<p><%= @weapon.title %></p>
<p><%= @weapon.description %></p>
<p><%= @weapon.power_base %></p>
<p><%= @weapon.power_step %></p>
<p><%= @weapon.current_power %></p>
<p><%= @weapon.level %></p>